### ISSUE TITLE
Service 'node-server' failed to build

### ISSUE THREAD

**Issue by GDur** [ntedgi/node-efficientnet#23]
**Describe the bug**
Tried to start the example but got the following error:

Step 5/8 : COPY package-lock.json /home/app/
ERROR: Service 'node-server' failed to build : COPY failed: file not found in build context or excluded by .dockerignore: stat package-lock.json: file does not exist

**To Reproduce**
1. Followed the Example guide
2. /node-efficientnet/playground> "docker-compose up" failed at step  5/8

**Expected behavior**
Server start

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by ntedgi** [comment]
Thanks @GDur for the issue submission  i tasted  the local environment only on ubuntu and osx let me check this issue

**Comment by GDur** [comment]
> try to run `npm install` inside the server dir
> and then run `docker-compose up` it seems like you need to have package.json lock file

Thanks! This fixed the problem.

Probably a good idea to add this step to the the example guide :)


Good Job on the project so far.
