### ISSUE TITLE
use i18n to translate output labels , add language to model options constractor

### ISSUE THREAD

**Issue by luoye-fe** [ntedgi/node-efficientnet#26]
**Is your feature request related to a problem? Please describe.**
multi-language label

**Describe the solution you'd like**
Human or Machine translation?

**Describe alternatives you've considered**

**Additional context**

**Comment by ntedgi** [comment]
great idea

**Comment by ntedgi** [comment]
https://www.npmjs.com/package/i18n

**Comment by luoye-fe** [comment]
by the way, where the `label map` from? Is it fixed in the model?

emm... did not find any information from google about efficientnet label.

**Comment by ntedgi** [comment]
The labels are from imagenet data set

**Comment by luoye-fe** [comment]
#32
