### ISSUE TITLE
 Configurable download address

### ISSUE THREAD

**Issue by luoye-fe** [ntedgi/node-efficientnet#27]
**Is your feature request related to a problem? Please describe.**
You know, downloading github assets in mainland China is particularly slow~

**Describe the solution you'd like**
Maybe, allow to specify local model dir? Such as:

```js
EfficientNetCheckPointFactory.create(EfficientNetCheckPoint.B7, {
  localModelRootDir: path.join(__dirname, 'tf-model'),
});
```

**Describe alternatives you've considered**

**Additional context**

**Comment by ntedgi** [comment]
should be enabled as part of #6

**Comment by luoye-fe** [comment]
#28
