### ISSUE TITLE
feature: Hebrew language support

### ISSUE THREAD

**Issue by ntedgi** [ntedgi/node-efficientnet#37]
today we only support English and Chinese label translations

translate image net labels to Hebrew
take https://github.com/ntedgi/node-efficientnet/blob/main/misc/en.json 
translate it to Hebrew using some machine or by hand

- add it to /misc folder

- add the ENUM and corresponding  case under EfficientNetLanguageProvider

- add minimal test for example :
```

test("EfficientNetLanguageProvider - check chinese translation file", (done) => {
  const chineseProvider = new EfficientNetLanguageProvider(
    EfficientNetLableLanguage.CHINESE
  );
  chineseProvider
    .load()
    .then(() => {
      const result = chineseProvider.get(0);
      expect(result).toBeDefined();
      expect(result).toEqual("丁鲷");
      done();
    })
    .catch((error) => done(error));
});
```
-  update readme file add the language support to  https://github.com/ntedgi/node-efficientnet#multilingual-status

**Comment by jhonDoe15** [comment]
Hi! could I be assigned to this issue please?
