### ISSUE TITLE
add support to CUSTOM_ELEMENTS_SCHEMA inside playground/ui

### ISSUE THREAD

**Issue by ntedgi** [ntedgi/node-efficientnet#64]
in order to clear warning from logs at ui tests runs and ignore angular warnings 
for example 
```

1. If 'p-fileUpload' is an Angular component, then verify that it is part of this module.
2. If 'p-fileUpload' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.'
```

add support to `CUSTOM_ELEMENTS_SCHEMA`

at playground/ui/src/app.module.ts

change 
`import { NgModule } from '@angular/core';
`to
`import { NgModule , CUSTOM_ELEMENTS_SCHEMA} from '@angular/core';`

and  add 
`  schemas: [CUSTOM_ELEMENTS_SCHEMA]` to 
@NgModule

the same as here

[ref](https://stackoverflow.com/a/39553713/4267015
)

**Comment by nancykwantify** [comment]
Hi there! May I work on this?

**Comment by ntedgi** [comment]
Thanks @nancykwantify
